DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd;
USE bd;

CREATE TABLE JUGADOR(
	ID VARCHAR(10) NOT NULL,
	NOMBRE VARCHAR(50),
	PASSWORD VARCHAR(15) NOT NULL,
	PRIMARY KEY(ID)
	)ENGINE = InnoDB;

CREATE TABLE PARTIDA(
	ID INT NOT NULL,
	DURACION INT,
	GANADOR VARCHAR(50),
	FECHA VARCHAR(50),
	PRIMARY KEY(ID)
	)ENGINE = InnoDB;
CREATE TABLE Lista_Partidas(
	PARTIDASTOTALES INTEGER NOT NULL,
	MVP VARCHAR(20) NOT NULL,
	TIEMPOMEDIO INTEGER NOT NULL
	FOREIGN KEY (MVP) REFERENCES JUGADOR(PARTIDAS_GANADAS)
	FOREIGN KEY (TIEMPOMEDIO) REFERENCES PARTIDA(DURACION)
	)ENGINE = InnoDB;


INSERT INTO JUGADOR VALUES("123S","Marc","12D");
INSERT INTO JUGADOR VALUES("783P","Edgar","85f");
INSERT INTO JUGADOR VALUES("756J","Carlos","8e9");

INSERT INTO PARTIDA VALUES(1,3,320,"Marc","2/9/24");
INSERT INTO PARTIDA VALUES(2,5,180,"Edgar","15/5/24");
INSERT INTO PARTIDA VALUES(3,3,260,"Carlos","18/8/24");

INSERT INTO Lista_Partidas VALUES (6, 'Marc', 120);
INSERT INTO Lista_Partidas VALUES (5, 'Edgar', 240);
INSERT INTO Lista_Partidas VALUES (4, 'Carlos', 480);

